name: Protected CD Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_password:
        description: "Enter deployment password"
        required: true
        type: string

jobs:
  deploy:
    if: ${{ github.event.inputs.deploy_password == 'MySecurePassword123' }}
    runs-on: ubuntu-latest

    steps:
      - name: Mask the input password in logs
        run: echo "::add-mask::${{ github.event.inputs.deploy_password }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy the app
        run: echo "🎉 CD process started. Deploying the app..."
